x-veld:
  code:
    description: "makes entire text lowercase"
    topic: 
      - "NLP"
      - "Preprocessing"
      - "ETL"

    input:
      - volume: /veld/input/
        environment_var: in_txt_file
        file_type: "txt"
        content: "raw text"

    output:
      - volume: /veld/output/data/
        environment_var: out_txt_file
        file_type: "txt"
        content: "raw text"
      - volume: /veld/output/metadata/
        environment_var: out_metdata_file
        file_type: "yaml"
        content: "metadata"

    config:
      - environment_var: out_data_description
        description: "textual data description used as output to the metadata veld yaml file"
        var_type: "str" 

services:
  veld_preprocess_lowercase:
    build: .
    volumes:
      - ./src/:/veld/code/:z
    command: python3 /veld/code/preprocess.py lowercase
    environment:
      in_txt_file: null
      out_txt_file: null
      out_metdata_file: null
      out_data_description: null
      cpu_count: null
      buffer_segments: 100
      sleep_duration: 10

