x-veld:
  code:
    description: "makes entire text lowercase"
    topic: 
      - "NLP"
      - "preprocessing"
      - "ETL"

    input:
      - volume: /veld/input/
        environment_var: in_txt_file
        file_type: "txt"
        content: "raw text"

    output:
      - volume: /veld/output/
        environment_var: out_txt_file 
        file_type: "txt"
        content: "raw text"

    config:
      - environment_var: out_data_description
        description: "automatic data description for generating a data veld yaml file"
        var_type: "str" 

services:
  veld_preprocess_lowercase:
    build: .
    volumes:
      - ./src/:/veld/code/:z
    command: python3 /veld/code/preprocess_lowercase.py
    environment:
      in_txt_file: null
      out_txt_file: null
      out_data_description: null

