x-veld:
  code:
    description: "removes punctuation from text with spaCy pretrained models"
    topics: 
      - "NLP"
      - "preprocessing"
      - "ETL"

    inputs:
      - volume: /veld/input/
        environment: in_txt_file
        file_type: "txt"
        contents: "raw text"

    outputs:
      - volume: /veld/output/
        environment: out_txt_file 
        file_type: "txt"
        contents: "raw text"

    settings:
      - environment: out_data_description
        description: "automatic data description for generating a data veld yaml file"
        env_type: "str" 
      - environment: cpu_count
        description: "number of cpu cores allocated to this processing. Defaults to maximum number
          of available cores"
        env_type: "int"
      - environment: buffer_segments
        description: "percentage of segments where processing results are persisted in between. So
          that processing could continue should it have crashed"
        env_type: "int"
        default: 100
      - environment: sleep_duration
        description: "number of seceonds between each multiprocess invokation, since with big data,
          a memory race condition can occurr. To work-around this, a small waiting period in between
          can be set with this variable."
        env_type: "int"
        default: 10

services:
  veld_preprocess_remove_punctuation:
    build: .
    volumes:
      - ./src/:/veld/code/:z
    command: python3 -u /veld/code/preprocess_remove_punctuation.py
    environment:
      in_txt_file: null
      out_txt_file: null
      cpu_count: null
      buffer_segments: 100
      out_data_description: null
      sleep_duration: 10

